# services:
#   postgres:
#     image: postgres:16
#     container_name: unstable-fusion-postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: my-secret-pw
#       POSTGRES_DB: sd_api
#       POSTGRES_USER: sduser
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U sduser -d sd_api"]
#       start_period: 10s
#       interval: 10s
#       timeout: 5s
#       retries: 3

  app:
    # image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11974796-unstable-fusion:latest
    build: .
    container_name: unstable-fusion-app
    restart: always
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - images_data:/app/generated_images
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  images_data: